Fixed import data csv
ALFA-9/Backend pull request #11
Opened 2024-01-25 20:51 UTC by Den2605

2024-01-25 22:34 UTC, aleksey2299-1 requested changes

2024-01-25 22:34 UTC, aleksey2299-1 commented on backend/tasks/views.py
> +    def create(self, request, *args, **kwargs):
Посмотри изначальный вариант create, там есть кое-что важное. Serializer.save() не просто так выведен в отдельный метод, мы конечно тут не особо придерживаемся данного метода, но возможно при рефакторинге будем. Метод SOLID

2024-01-25 22:34 UTC, aleksey2299-1 commented on backend/tasks/management/commands/control_csv.py
> +import csv
7 x (CTRL + C -> CTRL + V) это как минимум жестко, как максимум не DRY

2024-01-25 22:34 UTC, aleksey2299-1 commented on backend/alpha_project/settings.py
> +from dotenv import load_dotenv
Опять оно тут, хотя в requirements.txt не появилось. Сразу же положит docker container. Вопрос все еще в силе, оно нам точно нужно? У меня прекрасно и без него работает

2024-01-26 06:43 UTC, Den2605 commented on backend/tasks/views.py
> +    def create(self, request, *args, **kwargs):
Тут незаконченный вариант)

2024-01-26 06:46 UTC, Den2605 commented on backend/alpha_project/settings.py
> +from dotenv import load_dotenv
Действительно нет, надо будет обновить requirements.txt. Без него у меня не запускается.

2024-01-26 06:47 UTC, Den2605 commented on backend/tasks/management/commands/control_csv.py
> +import csv
Возможно, но данные нужны.

2024-01-26 12:07 UTC, closed without merging